name: Epic Free Games Notifier

on:
  schedule:
    # Запуск щодня о 09:22 UTC (це 12:22 за літнім Київським часом)
    - cron: '22 9 * * *'
  workflow_dispatch: # Дозволяє запускати вручну для тестування

jobs:
  check-epic:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: npm run start:epic
